import type { Metadata } from 'next';
import '../globals.css';
import { ToastContainer } from 'react-toastify';
import Navbar from '@/components/custom/navbar/navbar';
import { ThemeProvider } from '../theme-provider';
import AuthProvider from '../auth-provider';
import Footer from '@/components/custom/footer/footer';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <head />
            <body>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <AuthProvider>
                        <ToastContainer />
                        <div className="min-h-screen dark:bg-gray-950 bg-gray-50 p-8">
                            <div className="fixed invert-100 dark:invert-0 inset-0 bg-[url('../public/background.png')] bg-cover bg-center opacity-40 blur-sm"></div>
                            <div className="relative z-10 max-w-6xl mx-auto">
                                <Navbar />
                                {children}
                            </div>
                        </div>

                        <div className="items-baseline">
                            <Footer />
                        </div>
                    </AuthProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
